services:
  db:
    image: mysql:8
    container_name: auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Authifydb
      MYSQL_USER: root
      MYSQL_PASSWORD: authify
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./Authify_backend
    container_name: auth-backend
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_DB: Authifydb
      MYSQL_USER: root
      MYSQL_PASSWORD: authify
    depends_on:
      - db

  frontend:
    build:
      context: ./authify_frontend
    container_name: auth-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
